spring:
  application:
    name: ecommerce-users

server:
  port: 8081

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8888/eureka/
  instance:
    hostname: localhost